services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: secret_santa
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        ports:
            - "8005:8000"
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - DB_HOST=mysql
            - DB_DATABASE=laravel
            - DB_USERNAME=laravel
            - DB_PASSWORD=laravel
        depends_on:
            mysql:
                condition: service_healthy
            mailhog:
                condition: service_started
        networks:
            - secret_santa_network
        command: sh -c "php artisan serve --host=0.0.0.0 --port=8000"

    mysql:
        image: mysql:8.0
        container_name: secret_santa_mysql
        restart: unless-stopped
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=laravel
            - MYSQL_USER=laravel
            - MYSQL_PASSWORD=laravel
        ports:
            - "3307:3306"
        networks:
            - secret_santa_network
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            interval: 5s
            retries: 2
        volumes:
            - mysql_data:/var/lib/mysql

    secret_santa_phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: secret_santa_phpmyadmin
        restart: unless-stopped
        ports:
            - "8098:80"
        environment:
            - PMA_HOST=mysql
            - MYSQL_ROOT_PASSWORD=root
        depends_on:
            - mysql
        networks:
            - secret_santa_network

    mailhog:
        image: mailhog/mailhog
        container_name: secret_santa_mailhog
        restart: unless-stopped
        ports:
            - "1026:1025"
            - "8026:8025"
        networks:
            - secret_santa_network

    xdebug:
        build:
            context: .
            dockerfile: Dockerfile.xdebug
        container_name: secret_santa_xdebug
        restart: unless-stopped
        volumes:
            - .:/var/www/html
        environment:
            - XDEBUG_MODE=debug
            - XDEBUG_CONFIG=client_host=host.docker.internal client_port=9003
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - secret_santa_network

networks:
    secret_santa_network:
        driver: bridge

volumes:
    mysql_data:
