FROM php:8.2-fpm

# Installer Xdebug
RUN pecl install xdebug \
    && docker-php-ext-enable xdebug

# Configurer Xdebug
COPY xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini

WORKDIR /var/www/html

CMD ["php-fpm"]
