services:
  app:
    image: php:8.2-fpm
    container_name: laravel_app
    restart: unless-stopped
    networks:
      - laravel_network
    depends_on:
      - db
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    environment:
      PHP_IDE_CONFIG: "serverName=laravel"
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: "client_host=host.docker.internal client_port=9003"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: >
      sh -c "docker-php-ext-install pdo pdo_mysql && pecl install xdebug && docker-php-ext-enable xdebug && php-fpm"

  web:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: laravel_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3315:3306"
    networks:
      - laravel_network
    volumes:
      - dbdata:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog
    container_name: laravel_mailhog
    restart: unless-stopped
    ports:
      - "8025:8025"  # Interface Web MailHog
      - "1025:1025"  # Port SMTP
    networks:
      - laravel_network

volumes:
  dbdata:

networks:
  laravel_network:
    driver: bridge
