version: '3.8'

services:
    laravel_app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        ports:
            - "8000:8000"
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - DB_HOST=laravel_mysql
            - DB_DATABASE=laravel
            - DB_USERNAME=root
            - DB_PASSWORD=root
        depends_on:
            laravel_mysql:
                condition: service_healthy
            mailhog:
                condition: service_started
        networks:
            - laravel_network
        command: php-fpm

    laravel_mysql:
        image: mysql:8.0
        container_name: laravel_mysql
        restart: unless-stopped
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=laravel
            - MYSQL_USER=laravel
            - MYSQL_PASSWORD=laravel
        ports:
            - "3306:3306"
        networks:
            - laravel_network
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            interval: 10s
            retries: 3
        volumes:
            - mysql_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: unless-stopped
        ports:
            - "8080:80"
        environment:
            - PMA_HOST=laravel_mysql
            - MYSQL_ROOT_PASSWORD=root
        depends_on:
            - laravel_mysql
        networks:
            - laravel_network

    mailhog:
        image: mailhog/mailhog
        container_name: mailhog
        restart: unless-stopped
        ports:
            - "1025:1025" # SMTP
            - "8025:8025" # Web UI
        networks:
            - laravel_network

    xdebug:
        image: php:8.2-fpm
        container_name: xdebug
        restart: unless-stopped
        volumes:
            - .:/var/www/html
        environment:
            - XDEBUG_MODE=debug
            - XDEBUG_CONFIG=client_host=host.docker.internal client_port=9003
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - laravel_network

networks:
    laravel_network:
        driver: bridge

volumes:
    mysql_data:
