name: Build

on:
  workflow_call:

jobs:
  install:
    uses: ./.github/workflows/install.yml

  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 📦 Install Node dependencies & Build assets
        run: |
          npm install
          npm run build
